DELETE http://localhost:3003/api/blogs/60eb023eb8ab959a5f6a8c99
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2MTEwZGQwZmY5ZjkyMmEzMjhhNDI3YjAiLCJpYXQiOjE2Mjg0OTUxMjZ9.u7Ylx6dBEZz_1WmpF0GLi4P1-aloeNNsc_XJhPmPq1k

###
